/*
 * pagarmecoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg



type CONFIGURATION interface {
        ServiceRefererName() string
        SetServiceRefererName(serviceRefererName   string)
        BasicAuthUserName() string
        SetBasicAuthUserName(basicAuthUserName   string)
        BasicAuthPassword() string
        SetBasicAuthPassword(basicAuthPassword   string)
}

/*
 * Factory for the CONFIGURATION interface returning CONFIGURATION_IMPL
 */
func NewCONFIGURATION() CONFIGURATION{
    configuration := new(CONFIGURATION_IMPL)
    return configuration
}